# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 11, 4, 16, 356214, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
